-- Migration 024: Keyword Rules Engine
--
-- Creates the keyword_rules table for admin-configurable keyword→category mappings.
-- Admin rules are loaded at runtime by the suggestion engine before the hardcoded sets.
-- Built-in rules are seeded from the existing KEYWORD_SETS for transparency (read-only).
--
-- match_type values:
--   contains      — keyword appears anywhere in the name (case-insensitive)
--   word          — keyword appears as a whole word (word boundaries)
--   starts_with   — name starts with keyword (case-insensitive)
--   number_before — a number immediately precedes the keyword (e.g. ML → 240ML, 360ML)

CREATE TABLE IF NOT EXISTS keyword_rules (
    id          SERIAL PRIMARY KEY,
    keyword     VARCHAR(200)  NOT NULL,
    match_type  VARCHAR(20)   NOT NULL DEFAULT 'contains'
                    CHECK (match_type IN ('contains', 'word', 'starts_with', 'number_before')),
    category    VARCHAR(50)   NOT NULL
                    CHECK (category IN (
                        'cpu', 'gpu', 'ram', 'motherboard', 'storage',
                        'psu', 'case', 'cooling', 'fan', 'thermal_paste'
                    )),
    source      VARCHAR(10)   NOT NULL CHECK (source IN ('admin', 'builtin')),
    created_by  INTEGER       REFERENCES admins (id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    UNIQUE (keyword, category, match_type)
);

CREATE INDEX IF NOT EXISTS idx_keyword_rules_source  ON keyword_rules (source);
CREATE INDEX IF NOT EXISTS idx_keyword_rules_keyword ON keyword_rules (keyword);

-- ── Seed built-in rules from KEYWORD_SETS ────────────────────────────────────
-- All built-in rules use match_type='contains' (same as the hardcoded scorer).
-- ON CONFLICT DO NOTHING makes this idempotent.

-- cooling
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('aio','contains','cooling','builtin'),
('liquid','contains','cooling','builtin'),
('radiator','contains','cooling','builtin'),
('kraken','contains','cooling','builtin'),
('h100','contains','cooling','builtin'),
('h115','contains','cooling','builtin'),
('h150','contains','cooling','builtin'),
('h170','contains','cooling','builtin'),
('le720','contains','cooling','builtin'),
('le520','contains','cooling','builtin'),
('le240','contains','cooling','builtin'),
('lq360','contains','cooling','builtin'),
('lq240','contains','cooling','builtin'),
('mystique','contains','cooling','builtin'),
('galahad','contains','cooling','builtin'),
('coreliquid','contains','cooling','builtin'),
('mirage','contains','cooling','builtin'),
('freezer ii','contains','cooling','builtin'),
('pure loop','contains','cooling','builtin'),
('lt520','contains','cooling','builtin'),
('lt720','contains','cooling','builtin'),
('rl360','contains','cooling','builtin'),
('strix lc','contains','cooling','builtin'),
('rog lc','contains','cooling','builtin'),
('refroidisseur liquide','contains','cooling','builtin'),
('watercooling','contains','cooling','builtin'),
('corefrozr','contains','cooling','builtin'),
('castle','contains','cooling','builtin'),
('castle 240','contains','cooling','builtin'),
('castle 360','contains','cooling','builtin'),
('aqua','contains','cooling','builtin'),
('ml one','contains','cooling','builtin'),
('ml ultra','contains','cooling','builtin'),
('ml lcd','contains','cooling','builtin'),
('ml-one','contains','cooling','builtin'),
('ml-lcd','contains','cooling','builtin'),
('sg 240ml','contains','cooling','builtin'),
('sg 360ml','contains','cooling','builtin'),
('240ml argb','contains','cooling','builtin'),
('360ml argb','contains','cooling','builtin'),
('ventirad','contains','cooling','builtin'),
('cooler','contains','cooling','builtin'),
('refroidissement','contains','cooling','builtin'),
('nh-d','contains','cooling','builtin'),
('nh-u','contains','cooling','builtin'),
('ak400','contains','cooling','builtin'),
('ak500','contains','cooling','builtin'),
('ak620','contains','cooling','builtin'),
('ak700','contains','cooling','builtin'),
('assassin','contains','cooling','builtin'),
('dark rock','contains','cooling','builtin'),
('shadow rock','contains','cooling','builtin'),
('gammaxx','contains','cooling','builtin'),
('hyper 212','contains','cooling','builtin'),
('arctic alpine','contains','cooling','builtin'),
('arctic freezer','contains','cooling','builtin'),
('ag200','contains','cooling','builtin'),
('ag300','contains','cooling','builtin'),
('ag400','contains','cooling','builtin'),
('aircooler','contains','cooling','builtin'),
('air cooler','contains','cooling','builtin'),
('cpu cooler','contains','cooling','builtin'),
('cpu fan','contains','cooling','builtin'),
('a30','contains','cooling','builtin'),
('a400 rgb','contains','cooling','builtin'),
('cylon 3','contains','cooling','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- fan
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('120mm','contains','fan','builtin'),
('140mm','contains','fan','builtin'),
('200mm','contains','fan','builtin'),
('pwm fan','contains','fan','builtin'),
('case fan','contains','fan','builtin'),
('chassis fan','contains','fan','builtin'),
('f120','contains','fan','builtin'),
('f140','contains','fan','builtin'),
('ll120','contains','fan','builtin'),
('ql120','contains','fan','builtin'),
('fd12','contains','fan','builtin'),
('fd14','contains','fan','builtin'),
('fk120','contains','fan','builtin'),
('light wings','contains','fan','builtin'),
('pure wings','contains','fan','builtin'),
('riing','contains','fan','builtin'),
('toughfan','contains','fan','builtin'),
('duo 12','contains','fan','builtin'),
('core plus','contains','fan','builtin'),
('arctic flow','contains','fan','builtin'),
('ventilateur','contains','fan','builtin'),
('fan pack','contains','fan','builtin'),
('triple pack','contains','fan','builtin'),
('dual pack','contains','fan','builtin'),
('twin pack','contains','fan','builtin'),
('argb fan','contains','fan','builtin'),
('rgb fan','contains','fan','builtin'),
('fp1-r','contains','fan','builtin'),
('mcpupro','contains','fan','builtin'),
('mcpu66','contains','fan','builtin'),
('vortex fcb','contains','fan','builtin'),
('sickleflow','contains','fan','builtin'),
('sicklefan','contains','fan','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- thermal_paste
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('thermal','contains','thermal_paste','builtin'),
('paste','contains','thermal_paste','builtin'),
('grizzly','contains','thermal_paste','builtin'),
('kryonaut','contains','thermal_paste','builtin'),
('conductonaut','contains','thermal_paste','builtin'),
('hydronaut','contains','thermal_paste','builtin'),
('aeronaut','contains','thermal_paste','builtin'),
('duronaut','contains','thermal_paste','builtin'),
('mx-4','contains','thermal_paste','builtin'),
('mx-6','contains','thermal_paste','builtin'),
('mx-7','contains','thermal_paste','builtin'),
('carbonaut','contains','thermal_paste','builtin'),
('kryosheet','contains','thermal_paste','builtin'),
('pate thermique','contains','thermal_paste','builtin'),
('pâte thermique','contains','thermal_paste','builtin'),
('thermal compound','contains','thermal_paste','builtin'),
('thermal grease','contains','thermal_paste','builtin'),
('contact frame','contains','thermal_paste','builtin'),
('sealing frame','contains','thermal_paste','builtin'),
('cleaning wipes','contains','thermal_paste','builtin'),
('mx cleaner','contains','thermal_paste','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- case
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('tower','contains','case','builtin'),
('boitier','contains','case','builtin'),
('boîtier','contains','case','builtin'),
('tempered glass','contains','case','builtin'),
('tg argb','contains','case','builtin'),
('mid tower','contains','case','builtin'),
('full tower','contains','case','builtin'),
('mini itx','contains','case','builtin'),
('micro atx','contains','case','builtin'),
('h510','contains','case','builtin'),
('h710','contains','case','builtin'),
('h9','contains','case','builtin'),
('h6','contains','case','builtin'),
('h5','contains','case','builtin'),
('h7','contains','case','builtin'),
('h210','contains','case','builtin'),
('h400','contains','case','builtin'),
('h440','contains','case','builtin'),
('nzxt h','contains','case','builtin'),
('h510i','contains','case','builtin'),
('h710i','contains','case','builtin'),
('o11','contains','case','builtin'),
('lancool','contains','case','builtin'),
('pc-o11','contains','case','builtin'),
('lian li o','contains','case','builtin'),
('torrent','contains','case','builtin'),
('north','contains','case','builtin'),
('define','contains','case','builtin'),
('meshify','contains','case','builtin'),
('pop air','contains','case','builtin'),
('pop mini','contains','case','builtin'),
('silent base','contains','case','builtin'),
('pure base','contains','case','builtin'),
('matrexx','contains','case','builtin'),
('ch510','contains','case','builtin'),
('ch560','contains','case','builtin'),
('cc560','contains','case','builtin'),
('cg580','contains','case','builtin'),
('cg530','contains','case','builtin'),
('xt-1','contains','case','builtin'),
('xt-2','contains','case','builtin'),
('a21','contains','case','builtin'),
('a31','contains','case','builtin'),
('ap201','contains','case','builtin'),
('ap202','contains','case','builtin'),
('gt301','contains','case','builtin'),
('gt302','contains','case','builtin'),
('proart pa','contains','case','builtin'),
('pano','contains','case','builtin'),
('forge','contains','case','builtin'),
('gungnir','contains','case','builtin'),
('sekira','contains','case','builtin'),
('mpg gungnir','contains','case','builtin'),
('mag pano','contains','case','builtin'),
('corsair 2500','contains','case','builtin'),
('corsair 3000','contains','case','builtin'),
('corsair 3500','contains','case','builtin'),
('corsair 4000','contains','case','builtin'),
('corsair 5000','contains','case','builtin'),
('corsair 6500','contains','case','builtin'),
('cx300 argb','contains','case','builtin'),
('3500x','contains','case','builtin'),
('6500d','contains','case','builtin'),
('4000d','contains','case','builtin'),
('5000d','contains','case','builtin'),
('aero one','contains','case','builtin'),
('cylon','contains','case','builtin'),
('shard','contains','case','builtin'),
('bolt','contains','case','builtin'),
('scape','contains','case','builtin'),
('mc500','contains','case','builtin'),
('mc51','contains','case','builtin'),
('mca','contains','case','builtin'),
('mcmesh','contains','case','builtin'),
('mcorb','contains','case','builtin'),
('mc61','contains','case','builtin'),
('masterbox','contains','case','builtin'),
('mastercase','contains','case','builtin'),
('silencio','contains','case','builtin'),
('haf','contains','case','builtin'),
('td500','contains','case','builtin'),
('cm 6500x','contains','case','builtin'),
('6500x','contains','case','builtin'),
('cm 6600x','contains','case','builtin'),
('view 31','contains','case','builtin'),
('view 51','contains','case','builtin'),
('level 20','contains','case','builtin'),
('core p','contains','case','builtin'),
('eclipse','contains','case','builtin'),
('enthoo','contains','case','builtin'),
('evolv','contains','case','builtin'),
('cougar mx','contains','case','builtin'),
('cougar mg','contains','case','builtin'),
('cougar qbx','contains','case','builtin'),
('apnx v1','contains','case','builtin'),
('apnx c1','contains','case','builtin'),
('antec c3','contains','case','builtin'),
('antec vcx','contains','case','builtin'),
('antec vx','contains','case','builtin'),
('tengri','contains','case','builtin'),
('hybrok shadow','contains','case','builtin'),
('1stplayer x','contains','case','builtin'),
('aorus c300','contains','case','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- motherboard
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('b450','contains','motherboard','builtin'),
('b550','contains','motherboard','builtin'),
('b650','contains','motherboard','builtin'),
('b760','contains','motherboard','builtin'),
('b850','contains','motherboard','builtin'),
('b860','contains','motherboard','builtin'),
('x570','contains','motherboard','builtin'),
('x670','contains','motherboard','builtin'),
('z690','contains','motherboard','builtin'),
('z790','contains','motherboard','builtin'),
('z890','contains','motherboard','builtin'),
('a520','contains','motherboard','builtin'),
('a620','contains','motherboard','builtin'),
('h610','contains','motherboard','builtin'),
('h670','contains','motherboard','builtin'),
('h770','contains','motherboard','builtin'),
('h470','contains','motherboard','builtin'),
('b460','contains','motherboard','builtin'),
('b560','contains','motherboard','builtin'),
('z590','contains','motherboard','builtin'),
('z490','contains','motherboard','builtin'),
('prime b','contains','motherboard','builtin'),
('prime x','contains','motherboard','builtin'),
('prime z','contains','motherboard','builtin'),
('prime h','contains','motherboard','builtin'),
('rog strix b','contains','motherboard','builtin'),
('rog strix x','contains','motherboard','builtin'),
('tuf gaming b','contains','motherboard','builtin'),
('tuf gaming x','contains','motherboard','builtin'),
('tuf gaming z','contains','motherboard','builtin'),
('meg x','contains','motherboard','builtin'),
('msi pro z','contains','motherboard','builtin'),
('msi mag b','contains','motherboard','builtin'),
('msi mag x','contains','motherboard','builtin'),
('aorus elite','contains','motherboard','builtin'),
('aorus master','contains','motherboard','builtin'),
('aorus pro','contains','motherboard','builtin'),
('tomahawk','contains','motherboard','builtin'),
('mortar','contains','motherboard','builtin'),
('unify','contains','motherboard','builtin'),
('phantom gaming','contains','motherboard','builtin'),
('steel legend','contains','motherboard','builtin'),
('carte mère','contains','motherboard','builtin'),
('motherboard','contains','motherboard','builtin'),
('mpg b650i','contains','motherboard','builtin'),
('b650i edge','contains','motherboard','builtin'),
('asrock b','contains','motherboard','builtin'),
('asrock x','contains','motherboard','builtin'),
('asrock a','contains','motherboard','builtin'),
('asrock h','contains','motherboard','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- storage
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('nvme','contains','storage','builtin'),
('ssd','contains','storage','builtin'),
('hdd','contains','storage','builtin'),
('m.2','contains','storage','builtin'),
('pcie','contains','storage','builtin'),
('sata','contains','storage','builtin'),
('barracuda','contains','storage','builtin'),
('firecuda','contains','storage','builtin'),
('sn850','contains','storage','builtin'),
('sn770','contains','storage','builtin'),
('nm790','contains','storage','builtin'),
('ns100','contains','storage','builtin'),
('870 evo','contains','storage','builtin'),
('980 pro','contains','storage','builtin'),
('990 pro','contains','storage','builtin'),
('nv2','contains','storage','builtin'),
('a400','contains','storage','builtin'),
('p3 nvme','contains','storage','builtin'),
('p5 nvme','contains','storage','builtin'),
('disque dur','contains','storage','builtin'),
('disque ssd','contains','storage','builtin'),
('wd blue','contains','storage','builtin'),
('wd black','contains','storage','builtin'),
('wd red','contains','storage','builtin'),
('ironwolf','contains','storage','builtin'),
('skyhawk','contains','storage','builtin'),
('su650','contains','storage','builtin'),
('sx6000','contains','storage','builtin'),
('gammix','contains','storage','builtin'),
('lame gammix','contains','storage','builtin'),
('kingston a400','contains','storage','builtin'),
('kingston a2000','contains','storage','builtin'),
('kingston nv','contains','storage','builtin'),
('lexar ns100','contains','storage','builtin'),
('lexar sl200','contains','storage','builtin'),
('ocpc mfl','contains','storage','builtin'),
('ocpc xtl','contains','storage','builtin'),
('pny cs900','contains','storage','builtin'),
('crucial p2','contains','storage','builtin'),
('crucial p3','contains','storage','builtin'),
('crucial e100','contains','storage','builtin'),
('toshiba p300','contains','storage','builtin'),
('wd caviar','contains','storage','builtin'),
('teamgroup gx2','contains','storage','builtin'),
('t-force delta rgb 1tb','contains','storage','builtin'),
('verbatim','contains','storage','builtin'),
('usb 3.0 2tb','contains','storage','builtin'),
('usb 3.0 4tb','contains','storage','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- ram
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('ddr4','contains','ram','builtin'),
('ddr5','contains','ram','builtin'),
('mhz','contains','ram','builtin'),
('vengeance','contains','ram','builtin'),
('ripjaws','contains','ram','builtin'),
('trident','contains','ram','builtin'),
('fury beast','contains','ram','builtin'),
('t-force','contains','ram','builtin'),
('ares ddr','contains','ram','builtin'),
('cl16','contains','ram','builtin'),
('cl30','contains','ram','builtin'),
('cl36','contains','ram','builtin'),
('dimm','contains','ram','builtin'),
('mémoire','contains','ram','builtin'),
('memory','contains','ram','builtin'),
('3200mhz','contains','ram','builtin'),
('3600mhz','contains','ram','builtin'),
('5600mhz','contains','ram','builtin'),
('6000mhz','contains','ram','builtin'),
('vengeance rgb pro','contains','ram','builtin'),
('vengeance rgb','contains','ram','builtin'),
('vengeance lpx','contains','ram','builtin'),
('teamgroup delta','contains','ram','builtin'),
('aorus rgb','contains','ram','builtin'),
('pc portable elite','contains','ram','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- psu
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('watt','contains','psu','builtin'),
('850w','contains','psu','builtin'),
('1000w','contains','psu','builtin'),
('750w','contains','psu','builtin'),
('650w','contains','psu','builtin'),
('550w','contains','psu','builtin'),
('450w','contains','psu','builtin'),
('300w','contains','psu','builtin'),
('modular','contains','psu','builtin'),
('80+','contains','psu','builtin'),
('gold','contains','psu','builtin'),
('platinum','contains','psu','builtin'),
('titanium','contains','psu','builtin'),
('bronze','contains','psu','builtin'),
('rm850','contains','psu','builtin'),
('rm1000','contains','psu','builtin'),
('hx1000','contains','psu','builtin'),
('focus gx','contains','psu','builtin'),
('straight power','contains','psu','builtin'),
('pure power','contains','psu','builtin'),
('toughpower','contains','psu','builtin'),
('alimentation','contains','psu','builtin'),
('power supply','contains','psu','builtin'),
('atx 3.0','contains','psu','builtin'),
('atx 3.1','contains','psu','builtin'),
('pq850','contains','psu','builtin'),
('pq1000','contains','psu','builtin'),
('mag a850','contains','psu','builtin'),
('mag a1000','contains','psu','builtin'),
('antec csk','contains','psu','builtin'),
('antec ne1000','contains','psu','builtin'),
('antec ne1300','contains','psu','builtin'),
('aero bronze','contains','psu','builtin'),
('aero bronze 650','contains','psu','builtin'),
('aero bronze 750','contains','psu','builtin'),
('anima apiii','contains','psu','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- gpu
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('rtx','contains','gpu','builtin'),
('gtx','contains','gpu','builtin'),
('radeon','contains','gpu','builtin'),
('rx 6','contains','gpu','builtin'),
('rx 7','contains','gpu','builtin'),
('rx 9','contains','gpu','builtin'),
('geforce','contains','gpu','builtin'),
('vram','contains','gpu','builtin'),
('gddr6','contains','gpu','builtin'),
('graphics','contains','gpu','builtin'),
('carte graphique','contains','gpu','builtin'),
('gpu','contains','gpu','builtin'),
('arc b580','contains','gpu','builtin'),
('arc b570','contains','gpu','builtin'),
('arc a770','contains','gpu','builtin'),
('arc a750','contains','gpu','builtin'),
('rx550','contains','gpu','builtin'),
('arktek rx','contains','gpu','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;

-- cpu
INSERT INTO keyword_rules (keyword, match_type, category, source) VALUES
('ryzen','contains','cpu','builtin'),
('core i','contains','cpu','builtin'),
('core ultra','contains','cpu','builtin'),
('threadripper','contains','cpu','builtin'),
('socket am','contains','cpu','builtin'),
('lga1700','contains','cpu','builtin'),
('lga1851','contains','cpu','builtin'),
('ghz','contains','cpu','builtin'),
('processeur','contains','cpu','builtin'),
('processor','contains','cpu','builtin'),
('i3-','contains','cpu','builtin'),
('i5-','contains','cpu','builtin'),
('i7-','contains','cpu','builtin'),
('i9-','contains','cpu','builtin'),
('athlon','contains','cpu','builtin'),
('pentium','contains','cpu','builtin'),
('celeron','contains','cpu','builtin'),
('i7-9700','contains','cpu','builtin')
ON CONFLICT (keyword, category, match_type) DO NOTHING;
